CREATE TABLE IF NOT EXISTS llx_rexelsync_customer_agreement (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer NOT NULL,
  external_key varchar(128) NOT NULL,
  customer_id varchar(32) NOT NULL,
  scope varchar(32) NOT NULL DEFAULT '',
  agreement_index integer DEFAULT 0 NOT NULL,
  sales_agreement_number varchar(64) NULL,
  sales_agreement_label varchar(255) NULL,
  supplier_code varchar(16) NULL,
  derogation_number varchar(64) NULL,
  application_start_date datetime NULL,
  application_end_date datetime NULL,
  amount_agreement double(24,8) NULL,
  available_amount double(24,8) NULL,
  agreement_origin varchar(64) NULL,
  datec datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat integer NULL,
  fk_user_modif integer NULL,
  UNIQUE INDEX uk_rexelsync_customer_agreement (entity, fk_soc, external_key),
  INDEX idx_rexelsync_customer_agreement_entity (entity),
  INDEX idx_rexelsync_customer_agreement_soc (fk_soc),
  INDEX idx_rexelsync_customer_agreement_customer (customer_id),
  INDEX idx_rexelsync_customer_agreement_number (sales_agreement_number),
  INDEX idx_rexelsync_customer_agreement_dates (application_start_date, application_end_date)
) ENGINE=innodb;