CREATE TABLE IF NOT EXISTS llx_rexelsync_customer_profile (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer NOT NULL,
  customer_id varchar(32) NOT NULL,
  scope varchar(32) NOT NULL DEFAULT '',
  branch_code varchar(16) NULL,
  customer_name varchar(255) NULL,
  siren varchar(32) NULL,
  nic varchar(32) NULL,
  commercial_contact_fullname varchar(255) NULL,
  commercial_contact_phone varchar(64) NULL,
  commercial_contact_email varchar(255) NULL,
  address varchar(255) NULL,
  address2 varchar(255) NULL,
  address3 varchar(255) NULL,
  zip varchar(25) NULL,
  town varchar(128) NULL,
  fk_pays integer NULL,
  country_code varchar(8) NULL,
  country_name varchar(128) NULL,
  datec datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat integer NULL,
  fk_user_modif integer NULL,
  UNIQUE INDEX uk_rexelsync_customer_profile (entity, fk_soc, customer_id, scope),
  INDEX idx_rexelsync_customer_profile_entity (entity),
  INDEX idx_rexelsync_customer_profile_soc (fk_soc),
  INDEX idx_rexelsync_customer_profile_customer (customer_id)
) ENGINE=innodb;