CREATE TABLE IF NOT EXISTS llx_rexelsync_customer_address (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer NOT NULL,
  external_key varchar(128) NOT NULL,
  customer_id varchar(32) NOT NULL,
  scope varchar(32) NOT NULL DEFAULT '',
  address_type varchar(16) NULL,
  address_index integer DEFAULT 0 NOT NULL,
  origin varchar(64) NULL,
  name varchar(255) NULL,
  address varchar(255) NULL,
  address2 varchar(255) NULL,
  address3 varchar(255) NULL,
  zip varchar(25) NULL,
  town varchar(128) NULL,
  fk_pays integer NULL,
  country_code varchar(8) NULL,
  country_code_iso3 varchar(3) NULL,
  country_name varchar(128) NULL,
  datec datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat integer NULL,
  fk_user_modif integer NULL,
  UNIQUE INDEX uk_rexelsync_customer_address (entity, fk_soc, external_key),
  INDEX idx_rexelsync_customer_address_entity (entity),
  INDEX idx_rexelsync_customer_address_soc (fk_soc),
  INDEX idx_rexelsync_customer_address_customer (customer_id),
  INDEX idx_rexelsync_customer_address_type (address_type)
) ENGINE=innodb;